function [devinfo,error] = loadCFG(filename)
%LOADCFG Loads configuration file for fNIRS device
%

% cfginfo = initCfginfo();

dummyv=0; %dummy out the actual function to put the details of this function on hold


if dummyv    
    %dummy function
    error=0;
    
    %% example of ninjaNIRS hardware cfg
    devinfo = struct(...
        'devID','ninjaNIRS', ...
        'commPort','COM8', ...
        'auxList',{{}}, ...
        'nAux',0, ...
        'nSrcs',8, ...
        'nDets', 8, ...        
        'LaserPowerControl','Binary', ...
        'AdjustableGain', 0, ...
        'AdjustableRate', 0, ...
        'AdjustableFrequency', 1, ...
        'Rate', 93, ...
        'nLambda', 2, ...
        'Wavelengths', [730,850] ...    
);

%% example of fNIRS1000 hardware cfg
    devinfo = struct(...
        'devID','ninjaNIRS', ...
        'commPort','COM8', ...
        'auxList',{'A','B','C','D','E'}, ...
        'nAux',5, ...
        'nSrcs',4, ...
        'nDets', 12, ...        
        'LaserPowerControl','Binary', ...
        'AdjustableGain', 0, ...
        'AdjustableRate', 0, ...
        'AdjustableFrequency', 0, ...
        'Rate', 250, ...
        'nLambda', 2, ...
        'Wavelengths', [730,850] ...    
);

    
else
    
    load(filename,'devinfo','-mat');
    if exist('devinfo','var')
       error=0;
    else
        error=1;        
    end
    %now validate the the required fields are there
    
end